# Site settings
title: Ngắm Chị Đẹp
email: ""
description: "Photo Journal"
url: "https://ngamchidep.fun"
baseurl: "/"
facebook_username: ""
twitter_username: ""
instagram_username: ""
share: true
resource:
  facebook: https://gitlab.com/5991303e7401210b708b4632b305678a/ZmFjZWJvb2suY29t/-/raw/main/
  instagram: https://gitlab.com/5991303e7401210b708b4632b305678a/aW5zdGFncmFtLmNvbQ/-/raw/main/
  clothers: https://gitlab.com/5991303e7401210b708b4632b305678a/Y2xvdGhlcw/-/raw/main/
# Owner/author information
owner:
  name:   photorama
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  # - GALLERY: "https://ngamchidep.fun/gallery/"  
  # - JOURNAL: "https://ngamchidep.fun/journal/"
  # - ABOUT: "https://ngamchidep.fun/about/"
  - INSTAGRAM: "https://ngamchidep.fun/instagram/"
  - FACEBOOK: "https://ngamchidep.fun/facebook/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
